name: CI

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15"
        env: true
    - name: ci
      run: ./ci.sh
